# Generated by Django 4.0.3 on 2022-03-08 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_entry_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='Batman/<built-in function id>'),
        ),
    ]
