# Generated by Django 4.0.3 on 2022-03-08 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0003_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to='Batman/<django.db.models.fields.DateTimeField>'),
        ),
    ]
