# Generated by Django 4.0.3 on 2022-03-08 22:12

from django.db import migrations, models
import journal.models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0004_alter_entry_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='image',
            field=models.ImageField(blank=True, upload_to=journal.models.user_directory_path),
        ),
    ]
