# Generated by Django 4.0.3 on 2022-03-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0005_alter_entry_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='activated',
            field=models.BooleanField(default=True),
        ),
    ]
