# Generated by Django 4.0.3 on 2022-03-09 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0006_entry_activated'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crypt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('entry', models.TextField()),
                ('iv', models.TextField()),
            ],
        ),
    ]
