# Generated by Django 4.0.3 on 2022-03-09 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0007_crypt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypt',
        ),
    ]
