# Generated by Django 4.0.3 on 2022-03-10 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0008_delete_crypt'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='starred',
            field=models.BooleanField(default=False),
        ),
    ]
