# Generated by Django 3.2.13 on 2022-05-27 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_auto_20220318_2104'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='entry',
            name='journal_ent_title_0ecec1_idx',
        ),
    ]
