# Generated by Django 3.2.13 on 2022-06-20 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0011_remove_entry_journal_ent_title_0ecec1_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionsStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joy', models.IntegerField()),
                ('disgust', models.IntegerField()),
                ('sadness', models.IntegerField()),
                ('surprise', models.IntegerField()),
                ('negative', models.IntegerField()),
                ('positive', models.IntegerField()),
                ('trust', models.IntegerField()),
                ('anticipation', models.IntegerField()),
                ('fear', models.IntegerField()),
                ('anger', models.IntegerField()),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.entry')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
