# Generated by Django 3.2.13 on 2022-06-20 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_emotionsstat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotionsstat',
            name='entry',
        ),
    ]
