# Generated by Django 3.2.13 on 2022-06-20 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_remove_emotionsstat_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotionsstat',
            name='anger',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='anticipation',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='disgust',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='fear',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='joy',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='negative',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='positive',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='sadness',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='surprise',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='emotionsstat',
            name='trust',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
