# Generated by Django 3.2.13 on 2022-06-28 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_auto_20220620_1654'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmotionsStat',
        ),
    ]
