# Generated by Django 3.2.13 on 2022-06-28 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0015_delete_emotionsstat'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='emotion',
            field=models.CharField(default=None, max_length=16),
            preserve_default=False,
        ),
    ]
