# Generated by Django 3.2.13 on 2022-06-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('Motivational', 'Motivational'), ('Experience', 'Experience'), ('Opinion-Based', 'Opionion-Based'), ('Uncategorized', 'Uncategorized')], default='Uncategorized', max_length=16),
        ),
    ]
