# Generated by Django 4.0.3 on 2022-03-08 22:22

import authentication.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default=True, upload_to=authentication.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='profile',
            name='join_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
