# Generated by Django 4.0.3 on 2022-03-09 18:47

import authentication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_profile_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='entry_key',
            field=models.CharField(max_length=16),
        ),
    ]
