# Generated by Django 4.0.3 on 2022-03-09 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_profile_entry_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='entry_key',
        ),
    ]
