# Generated by Django 3.2.12 on 2022-04-02 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_alter_profile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('join_date',)},
        ),
    ]
