# Generated by Django 3.2.13 on 2022-06-13 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20220614_0107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favmoviefield',
            name='field',
            field=models.CharField(default='All', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='unfavmoviefield',
            name='field',
            field=models.CharField(choices=[('Ass', 'Ass'), ('Butt', 'Butt')], max_length=16, null=True),
        ),
    ]
