# Generated by Django 3.2.13 on 2022-06-13 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0016_auto_20220614_0217'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FavMovieField',
            new_name='MovieField',
        ),
        migrations.RenameModel(
            old_name='FavMusicField',
            new_name='MusicField',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disliked_movie_genres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='disliked_music_genres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_movie_genres',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='favourite_music_genres',
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_movie_genres',
            field=models.ManyToManyField(related_name='favourite_movie', to='authentication.MovieField'),
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_music_genres',
            field=models.ManyToManyField(related_name='favourite_music', to='authentication.MusicField'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unfav_movie_genres',
            field=models.ManyToManyField(related_name='unfavourite_movie', to='authentication.MovieField'),
        ),
        migrations.AddField(
            model_name='profile',
            name='unfav_music_genres',
            field=models.ManyToManyField(related_name='unfavourite_music', to='authentication.MusicField'),
        ),
        migrations.DeleteModel(
            name='UnFavMovieField',
        ),
        migrations.DeleteModel(
            name='UnFavMusicField',
        ),
    ]
