# Generated by Django 3.2.13 on 2022-06-20 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0018_frequencystatistics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencystatistics',
            name='active_time',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
