# Generated by Django 3.2.13 on 2022-06-28 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0019_alter_frequencystatistics_active_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrequencyStatistics',
        ),
    ]
