# Generated by Django 3.2.13 on 2022-06-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0021_profile_personality'),
    ]

    operations = [
        migrations.CreateModel(
            name='HobbyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(default='None', max_length=16, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='fav_movie',
            field=models.CharField(default=None, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='moviefield',
            name='field',
            field=models.CharField(default='None', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='musicfield',
            name='field',
            field=models.CharField(default='None', max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='hobby',
            field=models.ManyToManyField(related_name='hobby', to='authentication.HobbyField'),
        ),
    ]
