# Generated by Django 3.2.13 on 2022-07-02 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incentive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registrar', models.BooleanField(default=False)),
                ('diarist1', models.BooleanField(default=False)),
                ('diarist2', models.BooleanField(default=False)),
                ('diarist3', models.BooleanField(default=False)),
                ('diarist4', models.BooleanField(default=False)),
                ('storyteller1', models.BooleanField(default=False)),
                ('storyteller2', models.BooleanField(default=False)),
                ('logger1', models.BooleanField(default=False)),
                ('logger2', models.BooleanField(default=False)),
                ('logger3', models.BooleanField(default=False)),
                ('logger4', models.BooleanField(default=False)),
                ('logger5', models.BooleanField(default=False)),
                ('muse1', models.BooleanField(default=False)),
                ('muse2', models.BooleanField(default=False)),
                ('muse3', models.BooleanField(default=False)),
                ('muse4', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
